### ISSUE TITLE
Exemplo de utilização do ID com código errado.

### ISSUE THREAD

**Issue by Tiago-Marques** [CIT-SWAT/Android-Guidelines#1]
Na Wiki em Code Style, onde falamos de ID, temos:

```
<TextView
    android:id="@+id/textview_user_profile
    android:width="wrap_content"
    android:height="wrap_content" />
```

O correto seria:

```
<TextView
    android:id="@+id/textview_user_profile
    android:layout_width="wrap_content"
    android:layout_height="wrap_content" />
```

Corrigido em: https://github.com/Tiago-Marques/Android-Guidelines/wiki
Use esse link para o merge: https://github.com/Tiago-Marques/Android-Guidelines.wiki.git

**Comment by Tiago-Marques** [comment]
@felipearimateia , @fernandocs  , @alissin  e @mobileswat  
O que vocês acham?

**Comment by mobileswat** [comment]
@Tiago-Marques obrigado pelo feedback! Os ajustes foram realizados:
https://github.com/CIT-SWAT/Android-Guidelines/wiki/04---Code-Style#3---xml-style

Obs: estava incorreto mesmo.

**Comment by Tiago-Marques** [comment]
Muito bom!
