### ISSUE TITLE
Primeiro exemplo do Javadoc pode ser melhorado

### ISSUE THREAD

**Issue by Tiago-Marques** [CIT-SWAT/Android-Guidelines#2]
Atualmente o primeiro exemplo do Java doc é:

```
/**
 * Descrição do método, qual é sua utilidade.
 *
 * @param userName - nome do usuário
 *
 * @return um String com o nome do usuário
 */
public String setUserName(String userName) {
    // código
    return <alguma coisa>;
}
```

Mesmo não sendo no foco do Javadoc , estou sugerindo um exemplo mais real sem perder o intuito:

```
/**
 * Descrição do método, qual é sua utilidade.
 *
 * @param lastName - Sobrenome do usuário
 *
 * @return um String com o nome completo do usuário
 */
public String getUserFullName(String lastName) {
    // código
    return this.firstName + lastName;
}
```

Pode ser visto em: https://github.com/Tiago-Marques/Android-Guidelines/wiki
Use esse link para o merge: https://github.com/Tiago-Marques/Android-Guidelines.wiki.git

**Comment by Tiago-Marques** [comment]
@felipearimateia , @fernandocs  , @alissin  e @mobileswat  
O que vocês acham?

**Comment by mobileswat** [comment]
@Tiago-Marques obrigado pelo feedback! Os ajustes foram realizados:
https://github.com/CIT-SWAT/Android-Guidelines/wiki/04---Code-Style#5---javadoc

Obs: nesse caso, modificamos um pouco a sugestão devido à concatenação de Strings.

**Comment by Tiago-Marques** [comment]
Muito bom !
